### ISSUE TITLE
v1.14 Release Checklist

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-io#148]
## Pre-release
* [x] update default version to `v1.14.0`
  * [x] docs
  * [x] contributor guide
* [x] Monitoring
  * [x] Add page about monitoring
  * [x] Add weaviate-examples example
  * [x] update list of all env vars
* [ ] Custom distances
  * [x] Add dedicated page about distances
  * [x] Explain how to set distance in schema page
  * [x] Replace `certainty` with `distance` (still list `certainty` for backward compatibility, but mark as deprecated)
* [x] API Namespacing 
  * [x] Update page with new beacon format
  * [x] On all CRUD /v1/objects/ operation update to new format. Still list old format as deprecated for compatiblity sake
  * [ ] Update all client examples
  
## Post-release
* [ ] update config gen
* [ ] update WCS
* [ ] update docker hash in examples repo
